#Deployment da aplicação web conversão temperatura

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: 
      containers:
      - name: web
        image: 04041994/conversao-temperatura:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
          # fazer testes de carga para calcular os resources
        resources:
          limits: 
            cpu: "0.2"
            memory: "32Mi"
          requests:
            cpu: "0.1"
            memory: "24Mi"
---

# Service para a aplicação web conversão temperatura

apiVersion: v1
kind: Service
metadata: 
  name: web
spec: 
  selector: 
    app: web
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort


